import RelativeRest_DeepPass17

/-!
# Referee-facing axiom audit

When this project is kernel-checked, these commands print the transitive axiom dependencies of the
headline formal statements.  There are no project-local axiom declarations in the source tree.
-/

#print axioms RelativeRest.reciprocal_weights_iff_four
#print axioms RelativeRest.solution_preserving_fixed_point_module
#print axioms RelativeRest.emMixed_rainich_square
#print axioms RelativeRest.boost_balance_exists_unique
#print axioms RelativeRest.unique_carrier_algebraic_conformal_factor
#print axioms RelativeRest.iyerWald_factorization
#print axioms RelativeRest.iyerWald_lambda_unique
#print axioms RelativeRest.iyerWald_lambda_nonzero
#print axioms RelativeRest.metricClockCovector_normalized
#print axioms RelativeRest.selfadjoint_carrier_forces_metric_clock
#print axioms RelativeRest.normalizedClockEquiv_unique
#print axioms RelativeRest.radar_decomposition_unique
#print axioms RelativeRest.relationalObservable_deriv
#print axioms RelativeRest.knLogChi_hasRadialDerivative
#print axioms RelativeRest.knPrincipalNullPlus_null
#print axioms RelativeRest.knFieldCarrier_Carter_observer_certificate
#print axioms RelativeRest.kerrNewman_curvature_to_mino
#print axioms RelativeRest.causalRadarTime_mono
#print axioms RelativeRest.jet_contraction_eq_minus_two_stress

#print axioms RelativeRest.maxwellStress_relative_scale
#print axioms RelativeRest.relativeResidual_onShell_eq_defect
#print axioms RelativeRest.relativeResidual_zero_iff_fixed_point
#print axioms RelativeRest.defect_even_iteratedDeriv_zero
#print axioms RelativeRest.defect_odd_iteratedDeriv_carrier

#print axioms RelativeRest.tensorRelativeResidual_zero_iff_fixed_point
#print axioms RelativeRest.tensorDefect_odd_iteratedDeriv_eq_first
#print axioms RelativeRest.null_pair_unit_radar_frame
#print axioms RelativeRest.null_eikonals_force_optical_metric

#print axioms RelativeRest.actionToOpticalLinear_unique
#print axioms RelativeRest.actionToOpticalLinear_intertwines_boost
#print axioms RelativeRest.clockTransport_zero_iff
#print axioms RelativeRest.frobeniusSpatialObstruction_zero_iff

#print axioms RelativeRest.canonicalClockCovector_unit
#print axioms RelativeRest.canonicalClock_reconstruction
#print axioms RelativeRest.canonicalClockUnit_unique
#print axioms RelativeRest.canonicalClockLineMap_unique

#print axioms RelativeRest.descendantOnRange_factorization
#print axioms RelativeRest.descendantOnRange_unique
#print axioms RelativeRest.characteristicLambda_nonzero
#print axioms RelativeRest.characteristicClockLine

#print axioms RelativeRest.forcedGlobalLocalClockEquiv_preserves_covector
#print axioms RelativeRest.forcedGlobalLocalClockEquiv_maps_unit
#print axioms RelativeRest.forcedGlobalLocalClockMap_unique
