import RelativeRest_DeepPass11

/-!
# Relative Rest: deep forced pass 12

Close the central scaling/defect chain.

This file derives:
* lambda/rho = exp(s) from the (u,s) parametrization;
* Maxwell stress relative scale lambda^2/rho^2 = exp(2s);
* the on-shell scaled Einstein--Maxwell residual equals -16 pi sinh(s) T;
* every even normal derivative of that odd defect vanishes at s=0;
* every odd normal derivative equals the same fixed carrier -16 pi T.

Thus the manuscript's full "value vanishes, odd jet survives on one line" pattern is explicit.
-/

noncomputable section

open Function Set

namespace RelativeRest

/-! ## A. Relative/common scale parametrization -/

def rhoUS (u s : ℝ) : ℝ :=
  Real.exp ((u - s) / 2)

def lambdaUS (u s : ℝ) : ℝ :=
  Real.exp ((u + s) / 2)

theorem lambda_div_rho_eq_exp
    (u s : ℝ) :
    lambdaUS u s / rhoUS u s = Real.exp s := by
  unfold lambdaUS rhoUS
  have hrho : Real.exp ((u - s) / 2) ≠ 0 :=
    ne_of_gt (Real.exp_pos _)
  apply (div_eq_iff hrho).2
  rw [← Real.exp_add]
  congr 1
  ring

/-- The relative Maxwell stress weight is independent of the common scale u. -/
theorem maxwellStress_relative_scale
    (u s : ℝ) :
    (lambdaUS u s)^2 / (rhoUS u s)^2 =
      Real.exp (2 * s) := by
  have hratio := lambda_div_rho_eq_exp u s
  have hrho : rhoUS u s ≠ 0 := by
    unfold rhoUS
    exact ne_of_gt (Real.exp_pos _)
  calc
    (lambdaUS u s)^2 / (rhoUS u s)^2
        = (lambdaUS u s / rhoUS u s)^2 := by
            field_simp [hrho]
    _ = (Real.exp s)^2 := by rw [hratio]
    _ = Real.exp (2 * s) := by
      rw [pow_two, ← Real.exp_add]
      congr 1
      ring

/-! ## B. Derive the odd defect from the scaled field-equation residual -/

def relativeResidual
    (G T s : ℝ) : ℝ :=
  Real.exp (-s) *
    (G - 8 * Real.pi * Real.exp (2 * s) * T)

theorem relativeResidual_onShell_eq_defect
    (G T s : ℝ)
    (hEinstein : G = 8 * Real.pi * T) :
    relativeResidual G T s = defect T s := by
  have hexp :
      Real.exp (-s) * Real.exp (2 * s) =
        Real.exp s := by
    rw [← Real.exp_add]
    congr 1
    ring
  rw [hEinstein]
  unfold relativeResidual defect
  rw [mul_sub, hexp]
  rw [← Real.cosh_sub_sinh s, ← Real.cosh_add_sinh s]
  ring

@[simp] theorem relativeResidual_onShell_zero
    (G T : ℝ)
    (hEinstein : G = 8 * Real.pi * T) :
    relativeResidual G T 0 = 0 := by
  rw [relativeResidual_onShell_eq_defect G T 0 hEinstein]
  exact defect_zero T

/-- On nonvacuum electrovac, preserving the scaled field equation forces the unique fixed point. -/
theorem relativeResidual_zero_iff_fixed_point
    (G T s : ℝ)
    (hEinstein : G = 8 * Real.pi * T)
    (hT : T ≠ 0) :
    relativeResidual G T s = 0 ↔ s = 0 := by
  rw [relativeResidual_onShell_eq_defect G T s hEinstein]
  unfold defect
  have hcoef : -16 * Real.pi * T ≠ 0 := by
    exact mul_ne_zero
      (mul_ne_zero (by norm_num) (ne_of_gt Real.pi_pos))
      hT
  constructor
  · intro h
    have hsinh : Real.sinh s = 0 := by
      have : (-16 * Real.pi * T) * Real.sinh s = 0 := by
        simpa [mul_assoc, mul_left_comm, mul_comm] using h
      exact (mul_eq_zero.mp this).resolve_left hcoef
    exact Real.sinh_eq_zero.mp hsinh
  · rintro rfl
    simp

/-! ## C. All normal jets of the odd defect -/

theorem defect_eq_const_mul_sinh
    (T : ℝ) :
    defect T =
      fun s => (-16 * Real.pi * T) * Real.sinh s := by
  funext s
  unfold defect
  ring

/-- Every even normal derivative of the odd defect vanishes at the fixed point. -/
theorem defect_even_iteratedDeriv_zero
    (T : ℝ) (n : ℕ) :
    iteratedDeriv (2 * n) (defect T) 0 = 0 := by
  rw [defect_eq_const_mul_sinh T]
  rw [iteratedDeriv_const_mul_field]
  rw [Real.iteratedDeriv_even_sinh]
  simp

/-- Every odd normal derivative equals the same carrier -16 pi T. -/
theorem defect_odd_iteratedDeriv_carrier
    (T : ℝ) (n : ℕ) :
    iteratedDeriv (2 * n + 1) (defect T) 0 =
      -16 * Real.pi * T := by
  rw [defect_eq_const_mul_sinh T]
  rw [iteratedDeriv_const_mul_field]
  rw [Real.iteratedDeriv_odd_sinh]
  simp

/-- Hence all odd normal derivatives lie on the single real line generated by the first jet. -/
theorem defect_odd_iteratedDeriv_eq_first
    (T : ℝ) (n : ℕ) :
    iteratedDeriv (2 * n + 1) (defect T) 0 =
      iteratedDeriv 1 (defect T) 0 := by
  rw [defect_odd_iteratedDeriv_carrier T n]
  simpa using defect_odd_iteratedDeriv_carrier T 0

/-! ## D. Tensor-component version of the complete jet pattern -/

def tensorRelativeResidual
    (G T : Tensor44) (s : ℝ) : Tensor44 :=
  fun i j => relativeResidual (G i j) (T i j) s

theorem tensorRelativeResidual_onShell_eq_tensorDefect
    (G T : Tensor44)
    (hEinstein : ∀ i j, G i j = 8 * Real.pi * T i j)
    (s : ℝ) :
    tensorRelativeResidual G T s = tensorDefect T s := by
  funext i j
  exact relativeResidual_onShell_eq_defect
    (G i j) (T i j) s (hEinstein i j)

theorem tensorDefect_even_iteratedDeriv_zero
    (T : Tensor44)
    (i j : Fin 4)
    (n : ℕ) :
    iteratedDeriv (2 * n)
      (fun s => tensorDefect T s i j) 0 = 0 := by
  change iteratedDeriv (2 * n) (defect (T i j)) 0 = 0
  exact defect_even_iteratedDeriv_zero (T i j) n

theorem tensorDefect_odd_iteratedDeriv_carrier
    (T : Tensor44)
    (i j : Fin 4)
    (n : ℕ) :
    iteratedDeriv (2 * n + 1)
      (fun s => tensorDefect T s i j) 0 =
      tensorJet T i j := by
  change iteratedDeriv (2 * n + 1)
    (defect (T i j)) 0 =
    -16 * Real.pi * T i j
  exact defect_odd_iteratedDeriv_carrier (T i j) n

end RelativeRest
