import RelativeRest_DeepPass30

/-!
# Referee-facing axiom audit

When this project is kernel-checked, these commands print the transitive axiom dependencies of the
headline formal statements.  There are no project-local axiom declarations in the source tree.
-/

#print axioms RelativeRest.reciprocal_weights_iff_four
#print axioms RelativeRest.solution_preserving_fixed_point_module
#print axioms RelativeRest.emMixed_rainich_square
#print axioms RelativeRest.boost_balance_exists_unique
#print axioms RelativeRest.unique_carrier_algebraic_conformal_factor
#print axioms RelativeRest.iyerWald_factorization
#print axioms RelativeRest.iyerWald_lambda_unique
#print axioms RelativeRest.iyerWald_lambda_nonzero
#print axioms RelativeRest.metricClockCovector_normalized
#print axioms RelativeRest.selfadjoint_carrier_forces_metric_clock
#print axioms RelativeRest.normalizedClockEquiv_unique
#print axioms RelativeRest.radar_decomposition_unique
#print axioms RelativeRest.relationalObservable_deriv
#print axioms RelativeRest.knLogChi_hasRadialDerivative
#print axioms RelativeRest.knPrincipalNullPlus_null
#print axioms RelativeRest.knFieldCarrier_Carter_observer_certificate
#print axioms RelativeRest.kerrNewman_curvature_to_mino
#print axioms RelativeRest.causalRadarTime_mono
#print axioms RelativeRest.jet_contraction_eq_minus_two_stress

#print axioms RelativeRest.maxwellStress_relative_scale
#print axioms RelativeRest.relativeResidual_onShell_eq_defect
#print axioms RelativeRest.relativeResidual_zero_iff_fixed_point
#print axioms RelativeRest.defect_even_iteratedDeriv_zero
#print axioms RelativeRest.defect_odd_iteratedDeriv_carrier

#print axioms RelativeRest.tensorRelativeResidual_zero_iff_fixed_point
#print axioms RelativeRest.tensorDefect_odd_iteratedDeriv_eq_first
#print axioms RelativeRest.null_pair_unit_radar_frame
#print axioms RelativeRest.null_eikonals_force_optical_metric

#print axioms RelativeRest.actionToOpticalLinear_unique
#print axioms RelativeRest.actionToOpticalLinear_intertwines_boost
#print axioms RelativeRest.clockTransport_zero_iff
#print axioms RelativeRest.frobeniusSpatialObstruction_zero_iff

#print axioms RelativeRest.canonicalClockCovector_unit
#print axioms RelativeRest.canonicalClock_reconstruction
#print axioms RelativeRest.canonicalClockUnit_unique
#print axioms RelativeRest.canonicalClockLineMap_unique

#print axioms RelativeRest.descendantOnRange_factorization
#print axioms RelativeRest.descendantOnRange_unique
#print axioms RelativeRest.characteristicLambda_nonzero
#print axioms RelativeRest.characteristicClockLine

#print axioms RelativeRest.forcedGlobalLocalClockEquiv_preserves_covector
#print axioms RelativeRest.forcedGlobalLocalClockEquiv_maps_unit
#print axioms RelativeRest.forcedGlobalLocalClockMap_unique

#print axioms RelativeRest.clock_rate_eq_four_sqrt_pi_energy
#print axioms RelativeRest.electromagnetic_clock_full_chain

#print axioms RelativeRest.kerrNewman_field_forces_Carter_Mino

#print axioms RelativeRest.action_rest_iff_optical_weight_rest
#print axioms RelativeRest.action_rest_iff_zero_relative_velocity
#print axioms RelativeRest.relative_rest_complete_certificate

#print axioms RelativeRest.involution_projector_planes_orthogonal
#print axioms RelativeRest.rainich_principal_planes_orthogonal

#print axioms RelativeRest.pureRadialObserverResponse_fixed_point_jet
#print axioms RelativeRest.carrier_ratio_eq_optical_velocity
#print axioms RelativeRest.defect_velocity_certificate

#print axioms RelativeRest.relativeScaleCovector_nonzero
#print axioms RelativeRest.linearizedActionResponse_factors_relative
#print axioms RelativeRest.linearizedActionResponse_kernel_eq_relative_kernel
#print axioms RelativeRest.relativeActionNormalUnit_normalized

#print axioms RelativeRest.canonicalClockDual_reconstruction
#print axioms RelativeRest.relativeNormalClockDualEquiv

#print axioms RelativeRest.pastEndpointSet_shift
#print axioms RelativeRest.causalThetaMinus_shift
#print axioms RelativeRest.causalThetaPlus_shift
#print axioms RelativeRest.causalRadar_origin_shift

#print axioms RelativeRest.localIWCarrier_nonzero
#print axioms RelativeRest.localIWResponse_coefficient_unique
#print axioms RelativeRest.metricLocalIW_coefficient_forced
#print axioms RelativeRest.metricLocalIW_unit_response

#print axioms RelativeRest.clockCoverForm_unique
#print axioms RelativeRest.clockCoverForm_eq_canonical
#print axioms RelativeRest.forced_clock_cover_certificate

#print axioms RelativeRest.tensorLinearizedActionResponse_relative_eq_jet
#print axioms RelativeRest.action_module_tensor_jet_certificate

#print axioms RelativeRest.accumulatedClock_deriv
#print axioms RelativeRest.clock_with_rate_unique_up_to_origin
#print axioms RelativeRest.clock_with_rate_and_origin_unique

#print axioms RelativeRest.chronometricMetric_unit_observer
#print axioms RelativeRest.chronometricMetric_dual_eq_metricClockCovector
#print axioms RelativeRest.local_chronometric_data_forced
